development:
  adapter: mysql
  user: root
  database: wb_development

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: wb_production
  user: root